export type IStudent = {
  id?: number;
  student_name_en: string;
  student_name_bn?: string | null;
  student_id?: string | null;
  mobile?: string | null;
  group_id: number;
  section_id?: number | null;
  class_id: number;
  shift_id: number;
  date_of_birth_en?: string | null;
  date_of_birth_bn?: string | null;
  roll?: number | null;
  category_id?: number | null;
  blood_group?: 'A' | 'A+' | 'A-' | 'B' | 'B+' | 'B-' | 'O' | 'O+' | 'O-' | 'AB' | 'AB+' | 'AB-' | null;
  gender?: string | null;
  national_id?: string | null;
  nationality?: string | null;
  religion?: string | null;
  session_id?: number | null;
  academic_year_id: number;
  admission_date?: string | null;
  student_photo?: string | null;
  father_name_en?: string | null;
  father_name_bn?: string | null;
  father_nid?: string | null;
  father_mobile?: string | null;
  father_dob_en?: string | null;
  father_dob_bn?: string | null;
  father_occupation_en?: string | null;
  father_occupation_bn?: string | null;
  father_income?: number | null;
  mother_name_en?: string | null;
  mother_name_bn?: string | null;
  mother_nid?: string | null;
  mother_mobile?: string | null;
  mother_dob_en?: string | null;
  mother_dob_bn?: string | null;
  mother_occupation_en?: string | null;
  mother_occupation_bn?: string | null;
  mother_income?: number | null;
  current_village_en?: string | null;
  current_village_bn?: string | null;
  current_post_office_en?: string | null;
  current_post_office_bn?: string | null;
  current_post_code?: string | null;
  current_district?: number | null;
  current_thana?: number | null;
  permanent_village_en?: string | null;
  permanent_village_bn?: string | null;
  permanent_post_office_en?: string | null;
  permanent_post_office_bn?: string | null;
  permanent_post_code?: string | null;
  permanent_district?: number | null;
  permanent_thana?: number | null;
  guardian_name_en?: string | null;
  guardian_name_bn?: string | null;
  guardian_address_en?: string | null;
  guardian_address_bn?: string | null;
  last_institution?: string | null;
  last_class?: string | null;
  registration_number?: string | null;
  result?: string | null;
  year_passed?: string | null;
  status: 'active' | 'inactive';
  password?: string | null;
  school_id: number;
};

export type IStudentFilters = {
  searchTerm?: string;
  student_name_en?: string;
  student_id?: string;
  mobile?: string;
  class_id?: number;
  group_id?: number;
  section_id?: number;
  shift_id?: number;
  academic_year_id?: number;
  status?: 'active' | 'inactive';
  school_id?: number;
};
